import type { Metadata } from "next";
import { Merriweather_Sans } from "next/font/google";
import "./globals.css";

const merriweather = Merriweather_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const RootLayout = ({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) => {
    return (
        <html suppressHydrationWarning={true} lang="en">
            <body
                suppressHydrationWarning={true}
                className={merriweather.className}
            >
                {children}
            </body>
        </html>
    );
};

export default RootLayout;
