import type { Metadata } from "next";
import { Merriweather_Sans } from "next/font/google";
import "../globals.css";

const merriweather = Merriweather_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
    params: { locale },
}: {
    children: React.ReactNode;
    params: { locale: string };
}) {
    return (
        <html suppressHydrationWarning={true} lang={locale}>
            <body
                suppressHydrationWarning={true}
                className={merriweather.className}
            >
                {children}
            </body>
        </html>
    );
}
